
package net.lantrack.framework.sysbase.entity;

import net.lantrack.framework.core.entity.BaseEntity;

import org.springframework.context.annotation.Description;


/**
 * 菜单表
 * 2018年1月8日
 * @author lin
 */
public class SysMenu extends BaseEntity<SysMenu> {
    /**
     * 
     */
    private Integer id;

    /**
     * 父级名称
     */
    private String parentName;

    /**
     * 全名
     */
    private String fullName;

    /**
     * 父id
     */
    private Integer parentId;

    /**
     * 所有父ids
     */
    private String parentIds;

    /**
     * 菜单名称
     */
    private String menuName;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 链接
     */
    private String href;

    /**
     * 权限类型（0菜单1按钮）
     */
    private String target;

    /**
     * 图标
     */
    private String iconimg;

    /**
     * 是否展示  默认不展示
     */
    private String isShow=YES;

    /**
     * 权限标示
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database table sys_menu
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menu
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public SysMenu(Integer id, String parentName, String fullName, Integer parentId,
            String parentIds, String menuName, Integer sort, String href, String target,
            String iconimg, String isShow, String permission, String createBy, String createDate,
            String updateBy, String updateDate, String remarks, String delFlag) {
        super(createBy, createDate, updateBy, updateDate, remarks, delFlag);
        this.id = id;
        this.parentName = parentName;
        this.fullName = fullName;
        this.parentId = parentId;
        this.parentIds = parentIds;
        this.menuName = menuName;
        this.sort = sort;
        this.href = href;
        this.target = target;
        this.iconimg = iconimg;
        this.isShow = isShow;
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table sys_menu
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public SysMenu() {
        super();
    }

    
    public SysMenu(Integer id, Integer parentId, String menuName) {
        super();
        this.id = id;
        this.parentId = parentId;
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    @Description("父级名称")
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.parent_name
     *
     * @param parentName the value for sys_menu.parent_name
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menu.full_name
     *
     * @return the value of sys_menu.full_name
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.full_name
     *
     * @param fullName the value for sys_menu.full_name
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    @Description("父级编号")
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.parent_id
     *
     * @param parentId the value for sys_menu.parent_id
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menu.parent_ids
     *
     * @return the value of sys_menu.parent_ids
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.parent_ids
     *
     * @param parentIds the value for sys_menu.parent_ids
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    @Description("菜单名称")
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.menu_name
     *
     * @param menuName the value for sys_menu.menu_name
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    
    @Description("排序号")
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.sort
     *
     * @param sort the value for sys_menu.sort
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Description("跳转链接")
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.href
     *
     * @param href the value for sys_menu.href
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column sys_menu.target
     *
     * @return the value of sys_menu.target
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.target
     *
     * @param target the value for sys_menu.target
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    @Description("图标")
    public String getIconimg() {
        return iconimg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.iconimg
     *
     * @param iconimg the value for sys_menu.iconimg
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setIconimg(String iconimg) {
        this.iconimg = iconimg == null ? null : iconimg.trim();
    }

    @Description("是否展示")
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.is_show
     *
     * @param isShow the value for sys_menu.is_show
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    @Description("权限标示")
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column sys_menu.permission
     *
     * @param permission the value for sys_menu.permission
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    @Override
    public String toString() {
        return "SysMenu [id=" + id + ", parentName=" + parentName + ", fullName=" + fullName
                + ", parentId=" + parentId + ", parentIds=" + parentIds + ", menuName=" + menuName
                + ", sort=" + sort + ", href=" + href + ", target=" + target + ", iconimg="
                + iconimg + ", isShow=" + isShow + ", permission=" + permission + "]";
    }

}
