package net.lantrack.framework.sysbase.dao;


import net.lantrack.framework.sysbase.entity.SysUpDownFile;
import net.lantrack.framework.sysbase.entity.SysUpDownFileExample;

import org.apache.ibatis.annotations.Param;

import java.util.List;



/**
 * 系统资源文件管理dao
 * 2018年1月4日
 * @author lin
 */
public interface SysUpDownFileDao{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    long countByExample(SysUpDownFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    int deleteByExample(SysUpDownFileExample example);

    /**
     * 通过主键删除
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    int insert(SysUpDownFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    int insertSelective(SysUpDownFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    List<SysUpDownFile> selectByExample(SysUpDownFileExample example);

    /**
     * 通过主键查询
     */
    SysUpDownFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysUpDownFile record, @Param("example") SysUpDownFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    int updateByExample(@Param("record") SysUpDownFile record, @Param("example") SysUpDownFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    int updateByPrimaryKeySelective(SysUpDownFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_updownfile
     *
     * @mbg.generated Sun Jan 07 22:08:20 CST 2018
     */
    int updateByPrimaryKey(SysUpDownFile record);   
}